@startuml
autonumber

title Browser location chnage

participant History #white
participant Hop #white
participant App #white

History -> Hop : location change
Hop -> App : (Route, Location)
@enduml

@startuml
autonumber

title Navigation

participant Elm #white
participant App #white
participant Hop #white
participant History #white

App -> Hop : navigateTo path
Hop -> History : change path
History --> Hop : Task
Hop --> App : Effects
App -> Elm : Task
@enduml

